---
title: "Testing visulisation"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(ggplot2)
library(plotly)
```

```{r}
data <- read_csv("visit_data.csv")
```

```{r}
# HN test BA7547

ba7547 <- data %>%
  filter(hn == "BA7547")

bp_long <- ba7547 %>%
      select(visit_date, bp_sys, bp_dia) %>%
      pivot_longer(cols = c(bp_sys, bp_dia), names_to = "bp_type", values_to = "bp_value") %>%
      mutate(bp_value = as.numeric(bp_value))
    
    ggplot(bp_long, aes(x = visit_date, y = bp_value, color = bp_type)) +
      geom_line() +
      geom_point() +
      labs(x = "Date", y = "Blood Pressure (mmHg)", color = "Type") +
      theme_minimal() 

```

```{r}
data %>%
    mutate(
      bp_sys = as.numeric(bp_sys),
      bp_dia = as.numeric(bp_dia),
      visit_date = lubridate::dmy(visit_date)
    ) %>%
    filter(!is.na(visit_date))
```

```{r}

patient <- read_csv("patient_data.csv")
visit <- read_csv("visit_data.csv")

patient <- patient %>%
  mutate(
    dob = format(as.Date(dob), "%d/%m/%Y"),
    daystart = format(as.Date(daystart), "%d/%m/%Y")
  )
# 106/ need to fixed
unique(patient$no)

patient %>% arrange(no)
```




```{r}


# Now use patient_test, not patient_info
max(patient$age, na.rm = TRUE)
min(patient$age, na.rm = TRUE)

patient_info %>%
  filter(!is.na(daystart)) %>%
  arrange((daystart)) %>%
  head()


# need to check age then need to remove it as it's mistake by human

patient %>%
  filter(age >= 100)
```

```{r}
patient_vis <- patient %>%
  mutate(
    age_group = case_when(
      age >= 25 & age < 35 ~ "25–34",
      age >= 35 & age < 45 ~ "35–44",
      age >= 45 & age < 55 ~ "45–54",
      age >= 55 & age < 65 ~ "55–64",
      age >= 65 & age < 75 ~ "65–74",
      age >= 75 & age < 85 ~ "75–84",
      age >= 85 & age < 90 ~ "85–89",
      age >= 90 ~ "90+",
      TRUE ~ NA_character_
    )
  )

table(patient_vis$age_group, useNA = "ifany")

patient_vis %>%
  filter(!is.na(age_group)) %>%
  ggplot(aes(x = age_group, fill = age_group)) +
  geom_bar() +
  scale_fill_brewer(palette = "Set2") +
  theme_bw() +
  labs(
    title = "Age Distribution",
    x = "Age Group",
    y = "Number of Patients"
  ) +
  theme(legend.position = "none") 
```

